# Project Name
TARGET = PegSequencer

# Sources
CPP_SOURCES = PegSequencer.cpp
CPP_SOURCES += ShiftOut.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy/
DAISYSP_DIR = ../../DaisySP/

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
